#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# global settings

yabai -m config external_bar               all:35:0     \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.2          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_animation_duration  0.3          \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                auto_padding               on           \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                10           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 10

# float system preferences
apps=(
    '^System Information$'
    '^System Preferences$'
    '^Calculator$'
    '^Tunnelblick$'
    'Python'
)

titles=(
    'Preferences$'
    'Settings$'
)

for app in "${apps[@]}"; do
    yabai -m rule --add app="${app}" manage=off
done

for title in "${titles[@]}"; do
    yabai -m rule --add title="${title}" manage=off
done

yabai -m config layout bsp

echo "yabai configuration loaded.."
